// Project data for projects.html.
//
// Two sections:
//   1) CURATED — hand-edited polished projects (often archive / completed).
//      Edit these freely. The /project-dashboard skill will NEVER touch them.
//   2) AUTO — regenerated by the project-dashboard skill from ~/projects.
//      Anything between AUTO-GENERATED-START and AUTO-GENERATED-END is overwritten.
//      Don't hand-edit inside the markers; your changes will be lost on next run.
//
// Schema per entry (all string unless noted):
//   slug      unique id, kebab-case
//   title     display name
//   status    "active" | "archive"
//   date      "YYYY-MM-DD" — last activity (active) or completion year (archive)
//   tags      array of short lowercase tags
//   blurb     1-2 sentence summary
//   page      relative URL of detail page, or "" if none
//   repo      external URL (GitHub etc.), or "" if none
//   photos    array of relative image paths, or []
//   src       "git" | "mtime" | "deployed" — for active rows only

window.PROJECTS = [

  // ---- CURATED ----------------------------------------------------------

  {
    slug: "haggadah",
    title: "Multilingual Haggadah",
    status: "archive",
    date: "2022",
    tags: ["writing", "design"],
    blurb: "Passover haggadah in Hebrew, English, and Chinese. Preserves tradition, adds historical context in margin notes, and ships with an extensive appendix. The answer to \"how do you raise a kid in a mixed Chinese-Jewish household?\" — 就这样.",
    page: "",
    repo: "https://github.com/jsharf/multilingual_haggadah",
    photos: [
      "projects/haggadah/haggadah_photo1.png",
      "projects/haggadah/haggadah_photo2.png",
      "projects/haggadah/haggadah_photo3.png"
    ]
  },
  {
    slug: "lasertag",
    title: "Lasertag PCB",
    status: "archive",
    date: "2022",
    tags: ["hardware", "pcb", "embedded"],
    blurb: "Designed, built, and coded a lasertag board.",
    page: "",
    repo: "",
    photos: [
      "projects/lasertag/during_soldering.jpg",
      "projects/lasertag/lasertagboard.jpg"
    ]
  },
  {
    slug: "automated-planter",
    title: "Automated Planter",
    status: "archive",
    date: "2022",
    tags: ["hardware", "embedded"],
    blurb: "Group project — automated indoor planter. I wrote the environment-control firmware and researched circuits for pump and valve control.",
    page: "",
    repo: "",
    photos: [
      "projects/automated_planter/pipes.jpg",
      "projects/automated_planter/showing_plants_and_fan.jpg"
    ]
  },
  {
    slug: "web-controlled-car",
    title: "Web-controlled RC Car",
    status: "archive",
    date: "2022",
    tags: ["hardware", "embedded", "web"],
    blurb: "RC car drivable from anywhere. Soldered a microcontroller to the car's remote for steering/throttle, then bridged it to an Azure backend over USB serial + websockets.",
    page: "",
    repo: "",
    photos: [
      "projects/web_controlled_car/solder_job.jpg"
    ],
    extras: [
      { label: "Demo video", href: "projects/web_controlled_car/demo.mp4" }
    ]
  },
  {
    slug: "retro-wireless-mouse",
    title: "Wireless Retro Apple Mouse",
    status: "archive",
    date: "2022",
    tags: ["hardware"],
    blurb: "Retrofitted an old retro Apple mouse with the electronics of a modern wireless mouse, including a 3D-printed housing for the new internals.",
    page: "",
    repo: "",
    photos: [
      "projects/retro_wireless_mouse/before.jpg",
      "projects/retro_wireless_mouse/insides.jpg",
      "projects/retro_wireless_mouse/mouse_outside.jpg"
    ],
    extras: [
      { label: "Demo video", href: "projects/retro_wireless_mouse/demo.mp4" }
    ]
  },
  {
    slug: "nishika",
    title: "Digital Nishika Remake",
    status: "archive",
    date: "2022",
    tags: ["hardware", "photo"],
    blurb: "Digital remake of the Nishika — an 80s film camera that captured one scene through several lenses to give a wiggling \"3D\" effect. Two cameras on a Pi, fixed to an acrylic harness, with a tiny Python script that combines frames into a back-and-forth gif.",
    page: "",
    repo: "",
    photos: [
      "projects/perspective_camera/camera_rig.jpg"
    ]
  },

  // ---- AUTO-GENERATED-START ----
  // Regenerated by the project-dashboard skill. Do not hand-edit.
  {
    slug: "attune",
    title: "Attune",
    status: "active",
    date: "2026-04-30",
    src: "git",
    tags: ["audio", "ml", "ux"],
    blurb: "Live focus coach: adaptive music + breath cues + TTS interventions, with a music-only mode. Recent UX pass — music-only gating, fatigue-loop fix, TTS rate cap.",
    page: "projects/attune.html",
    repo: "https://github.com/jsharf/attune",
    photos: []
  },
  {
    slug: "daily-brief",
    title: "Daily Brief",
    status: "active",
    date: "2026-05-01",
    src: "mtime",
    tags: ["software", "productivity", "ai"],
    blurb: "Morning-paper printer. Pulls news, calendar, weather, Hacker News with LLM-curated pull-quotes; renders a two-column XeLaTeX broadsheet with QR codes; AirPrints at 8am.",
    page: "projects/daily-brief.html",
    repo: "",
    photos: []
  },
  {
    slug: "echess",
    title: "echess — Electromagnetic Chessboard",
    status: "active",
    date: "2026-04-17",
    src: "git",
    tags: ["hardware", "pcb"],
    blurb: "Chessboard with magnetic pieces moved by a grid of PCB coils underneath. Now generating JLCPCB-ready Gerbers for the 5x5 coreless coil board.",
    page: "projects/echess.html",
    repo: "https://github.com/jsharf/echess",
    photos: []
  },
  {
    slug: "chinese-reader-app",
    title: "Chinese Reader App",
    status: "active",
    date: "2026-05-01",
    src: "mtime",
    tags: ["app", "language", "ml"],
    blurb: "Reader app for studying Chinese — long-press a word for pinyin + translation, TTS that highlights the current word, and a content pipeline that pulls and re-grades source material. Pivoted from Flutter to Expo/React Native.",
    page: "projects/chinese-reader-app.html",
    repo: "",
    photos: []
  },
  {
    slug: "507-priorities",
    title: "11 USC 507 Priority Checker",
    status: "active",
    date: "2026-04-30",
    src: "deployed",
    tags: ["web", "law"],
    blurb: "Interactive priority checker for 11 U.S.C. § 507 bankruptcy claim ordering. Already live at /507-priorities.html.",
    page: "/507-priorities.html",
    repo: "",
    photos: []
  }
  // ---- AUTO-GENERATED-END ----
];
